# Generated by Django 4.1 on 2022-09-22 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmodel',
            name='cv',
        ),
    ]
